CREATE TABLE `board` (
  `no` int NOT NULL AUTO_INCREMENT,
  `id` varchar(100) NOT NULL,
  `title` varchar(100) NOT NULL,
  `writer` varchar(100) NOT NULL,
  `content` text,
  `reg_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `upd_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`no`)
) COMMENT='게시판';

INSERT INTO `board` (`id`, `title`, `writer`, `content`) 
VALUES ('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content'),
('id' ,'title', 'writer', 'content');